In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline
plt.style.use('default')
plt.rcParams['figure.figsize'] = (22, 10)
sns.set(style="whitegrid")
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('./events_up_to_01062018.csv', low_memory=False)
df.head()

,timestamp,event,person,url,sku,model,condition,storage,color,skus,...,search_engine,channel,new_vs_returning,city,region,country,device_type,screen_resolution,operating_system_version,browser_version
0,2018-05-18 00:11:59,viewed product,4886f805,NaN,9288.0,Samsung Galaxy J7 Prime,Excelente,32GB,Dourado,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2018-05-18 00:11:27,viewed product,ad93850f,NaN,304.0,iPhone 5s,Muito Bom,32GB,Cinza espacial,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2018-05-18 00:11:16,viewed product,0297fc1e,NaN,6888.0,iPhone 6S,Muito Bom,64GB,Prateado,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2018-05-18 00:11:14,viewed product,2d681dd8,NaN,11890.0,iPhone 7,Bom,128GB,Vermelho,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2018-05-18 00:11:09,viewed product,cccea85e,NaN,7517.0,LG G4 H818P,Excelente,32GB,Branco,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df_eventos = df.filter(items = ["event","person"])
df_eventos.head()

            event    person
0  viewed product  4886f805
1  viewed product  ad93850f
2  viewed product  0297fc1e
3  viewed product  2d681dd8
4  viewed product  cccea85e

In [4]:
df_eventos.event.value_counts()

viewed product       1248124
brand listing         216312
visited site          204069
ad campaign hit       191388
generic listing       160176
searched products     130616
search engine hit     106406
checkout               65315
staticpage             11201
conversion              7091
lead                     983
Name: event, dtype: int64

In [5]:
labels = pd.read_csv('./labels_training_set.csv', low_memory=False)
labels.head()

     person  label
0  0566e9c1      0
1  6ec7ee77      0
2  abe7a2fb      0
3  34728364      0
4  87ed62de      0

In [6]:
labels.label.value_counts()

0    18434
1      980
Name: label, dtype: int64

In [7]:
sin_compra = labels.loc[labels.label == 0]
sin_compra["Cant"] = 1
sin_compra.groupby(["person"]).agg({"Cant":"sum"}).reset_index().sort_values(by="Cant",ascending=False).head()

         person  Cant
0      0008ed71     1
13825  c0f66132     1
12293  ac2ca825     1
12292  ac22adba     1
12291  ac201b9a     1

In [8]:
df.loc[df.event == "brand listing"].head()

,timestamp,event,person,url,sku,model,condition,storage,color,skus,...,search_engine,channel,new_vs_returning,city,region,country,device_type,screen_resolution,operating_system_version,browser_version
1760143,2018-02-09 20:10:22,brand listing,4115546b,NaN,NaN,NaN,NaN,NaN,NaN,"3191,6819,2783,8135,2778,2725,12436,4477,2782,...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1760145,2018-02-09 20:18:16,brand listing,4115546b,NaN,NaN,NaN,NaN,NaN,NaN,"3191,6819,2783,8135,2778,2725,12436,4477,2782,...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1760148,2018-02-09 20:24:59,brand listing,59dd7001,NaN,NaN,NaN,NaN,NaN,NaN,"7966,2927,10435,7826,3000,10462,9175,725,12535...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1760149,2018-02-09 20:27:23,brand listing,59dd7001,NaN,NaN,NaN,NaN,NaN,NaN,"3191,6819,2783,8135,2778,2725,3179,12436,4477,...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1760150,2018-02-09 20:25:59,brand listing,59dd7001,NaN,NaN,NaN,NaN,NaN,NaN,"7966,2927,10435,7826,3000,10462,9175,725,12535...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
na  = df.loc[df.event == "staticpage"].head()
na.loc[:, ["person","staticpage"]]

       person   staticpage
25   ec9c4059   Conditions
67   a08d42ea      AboutUs
86   ec9c4059  how-to-sell
520  6972936f      AboutUs
554  6972936f  how-to-sell

In [10]:
person_conversion = df #.loc[(df.event == "conversion") | (df.event == "lead") | (df.event == "checkout") ]
person_conversion.head()

,timestamp,event,person,url,sku,model,condition,storage,color,skus,...,search_engine,channel,new_vs_returning,city,region,country,device_type,screen_resolution,operating_system_version,browser_version
0,2018-05-18 00:11:59,viewed product,4886f805,NaN,9288.0,Samsung Galaxy J7 Prime,Excelente,32GB,Dourado,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2018-05-18 00:11:27,viewed product,ad93850f,NaN,304.0,iPhone 5s,Muito Bom,32GB,Cinza espacial,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2018-05-18 00:11:16,viewed product,0297fc1e,NaN,6888.0,iPhone 6S,Muito Bom,64GB,Prateado,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2018-05-18 00:11:14,viewed product,2d681dd8,NaN,11890.0,iPhone 7,Bom,128GB,Vermelho,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2018-05-18 00:11:09,viewed product,cccea85e,NaN,7517.0,LG G4 H818P,Excelente,32GB,Branco,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
person_conversion["CantidadConv"] = person_conversion.event == "conversion"
person_conversion["CantidadLead"] = person_conversion.event == "lead"
person_conversion["CantidadChekout"] = person_conversion.event == "checkout"
person_conversion["CantidadEventos"] = 1

In [12]:
person_eventos_compras = person_conversion.groupby("person").agg({"CantidadConv":"sum", "CantidadChekout":"sum", "CantidadLead":"sum"}).reset_index()

In [13]:
person_conversion.groupby("person").agg({"CantidadConv":"mean", "CantidadChekout":"mean", "CantidadLead":"mean"}).reset_index()

         person  CantidadConv  CantidadChekout  CantidadLead
0      0008ed71      0.000000         0.500000           0.0
1      00091926      0.000000         0.004464           0.0
2      00091a7a      0.000000         0.000000           0.0
3      000ba417      0.004854         0.029126           0.0
4      000c79fe      0.000000         0.058824           0.0
5      000e4d9e      0.000000         0.002433           0.0
6      000e619d      0.000000         0.014706           0.0
7      001001be      0.014706         0.044118           0.0
8      0010e89a      0.000000         0.250000           0.0
9      0016c4b5      0.000000         0.250000           0.0
10     001802e4      0.000000         0.052632           0.0
11     001804a2      0.250000         0.500000           0.0
12     0019e639      0.004246         0.031847           0.0
13     001a2273      0.000000         0.062500           0.0
14     001b0bf9      0.142857         0.285714           0.0
15     001ca5ee      0.000000         0.010417           0.0
16     001dfc31      0.000000         0.000000           0.0
17     001e9aea      0.000000         0.055556           0.0
18     0020152e      0.111111         0.222222           0.0
19     00202cdb      0.000000         0.066667           0.0
20     0022965d      0.000000         0.042328           0.0
21     0027574e      0.000000         0.019231           0.0
22     00295d74      0.000000         0.111111           0.0
23     002aea56      0.014134         0.038869           0.0
24     002b0188      0.000000         0.026316           0.0
25     002e74b2      0.000000         0.125000           0.0
26     002ed810      0.035088         0.035088           0.0
27     002fb981      0.000000         0.020000           0.0
28     00317e49      0.000000         0.076923           0.0
29     0031c75f      0.000000         0.035714           0.0
...         ...           ...              ...           ...
38799  ffcaae19      0.000000         0.032258           0.0
38800  ffcaeaae      0.000000         0.000000           0.0
38801  ffccd5a1      0.000000         0.153846           0.0
38802  ffcf952b      0.000000         0.011494           0.0
38803  ffd41214      0.000000         0.000000           0.0
38804  ffd62616      0.009434         0.009434           0.0
38805  ffd9756a      0.000000         0.125000           0.0
38806  ffda14ca      0.000000         0.250000           0.0
38807  ffdafc72      0.029412         0.058824           0.0
38808  ffddd0ec      0.000000         0.000000           0.0
38809  ffde3628      0.000000         0.009615           0.0
38810  ffe066cc      0.000000         0.018182           0.0
38811  ffe53446      0.011628         0.029070           0.0
38812  ffe7e848      0.000000         0.056075           0.0
38813  ffeb80c5      0.000000         0.125000           0.0
38814  ffebdbc9      0.000000         0.035714           0.0
38815  ffecdf29      0.000000         0.250000           0.0
38816  ffecea3d      0.000000         0.000000           0.0
38817  ffed0342      0.003049         0.021341           0.0
38818  ffed3d0e      0.000000         0.125000           0.0
38819  ffee0f18      0.000000         0.000578           0.0
38820  ffef83e6      0.000000         0.004630           0.0
38821  fff1659c      0.000000         0.054545           0.0
38822  fff1b11a      0.000000         0.000000           0.0
38823  fff1caee      0.000000         0.250000           0.0
38824  fff2bdde      0.017544         0.070175           0.0
38825  fff54d61      0.000000         0.000000           0.0
38826  fff72025      0.010309         0.010309           0.0
38827  fff78145      0.000000         0.042553           0.0
38828  fffd1246      0.000000         0.100000           0.0

[38829 rows x 4 columns]

In [14]:
person_eventos_compras.CantidadLead.mean()

0.025316129696876046

In [15]:
person_Ff = df.loc[df.person == "000ba417"]
person_Ff.event.value_counts()

viewed product       153
brand listing         24
generic listing       14
checkout               6
visited site           6
search engine hit      1
conversion             1
ad campaign hit        1
Name: event, dtype: int64

In [16]:
person_eventos = df.groupby("person").agg({"event":"count"})
person_eventos

          event
person
0008ed71      6
00091926    448
00091a7a     10
000ba417    206
000c79fe     17
000e4d9e    411
000e619d     68
001001be     68
0010e89a      4
0016c4b5      4
001802e4     19
001804a2      4
0019e639    471
001a2273     16
001b0bf9      7
001ca5ee     96
001dfc31     35
001e9aea     54
0020152e      9
00202cdb     30
0022965d    189
0027574e    156
00295d74     18
002aea56    283
002b0188     38
002e74b2      8
002ed810     57
002fb981     50
00317e49     13
0031c75f     56
...         ...
ffcaae19     31
ffcaeaae     22
ffccd5a1     26
ffcf952b     87
ffd41214     36
ffd62616    106
ffd9756a      8
ffda14ca      4
ffdafc72     34
ffddd0ec     33
ffde3628    208
ffe066cc     55
ffe53446    172
ffe7e848    107
ffeb80c5      8
ffebdbc9     28
ffecdf29     12
ffecea3d     10
ffed0342    328
ffed3d0e      8
ffee0f18   3458
ffef83e6    216
fff1659c     55
fff1b11a     21
fff1caee      4
fff2bdde     57
fff54d61      2
fff72025     97
fff78145     47
fffd1246     10

[38829 rows x 1 columns]

In [17]:
person_eventos.mean()

event    60.307528
dtype: float64

Vamos a calificar cuales usuarios son mas propensos a tener eventos de compras, estos eventos van a ser los eventos tipo; conversion, checkout.

Lo podemos dividir en compradores:
    1)Frecuentes - Promedio mayor a 0.6
    2)Esporadicos - Promedio mayor a 0.2  menor a 0.6
    3)Casi nunca - Promedio menor a 0.2
    3)Nunca - Promedio 0

In [18]:
person_checkout_conversion = df.loc[(df.event == "conversion") | (df.event == "checkout") ]
person_checkout_conversion["CantidadConv"] = (person_conversion.event == "conversion")
person_checkout_conversion["CantidadChekout"] = (person_conversion.event == "checkout")
person_checkout_conversion = person_checkout_conversion.groupby("person").agg({"CantidadConv":"sum", "CantidadChekout":"sum"}).reset_index()
person_checkout_conversion

         person  CantidadConv  CantidadChekout
0      0008ed71           0.0              3.0
1      00091926           0.0              2.0
2      000ba417           1.0              6.0
3      000c79fe           0.0              1.0
4      000e4d9e           0.0              1.0
5      000e619d           0.0              1.0
6      001001be           1.0              3.0
7      0010e89a           0.0              1.0
8      0016c4b5           0.0              1.0
9      001802e4           0.0              1.0
10     001804a2           1.0              2.0
11     0019e639           2.0             15.0
12     001a2273           0.0              1.0
13     001b0bf9           1.0              2.0
14     001ca5ee           0.0              1.0
15     001e9aea           0.0              3.0
16     0020152e           1.0              2.0
17     00202cdb           0.0              2.0
18     0022965d           0.0              8.0
19     0027574e           0.0              3.0
20     00295d74           0.0              2.0
21     002aea56           4.0             11.0
22     002b0188           0.0              1.0
23     002e74b2           0.0              1.0
24     002ed810           2.0              2.0
25     002fb981           0.0              1.0
26     00317e49           0.0              1.0
27     0031c75f           0.0              2.0
28     00344873           0.0              1.0
29     003847fc           0.0              2.0
...         ...           ...              ...
32842  ffbb282f           0.0              1.0
32843  ffbb90a9           0.0              1.0
32844  ffbfc511           0.0              1.0
32845  ffc0f2a0           0.0              4.0
32846  ffc51f07           0.0              1.0
32847  ffc670b3           2.0              7.0
32848  ffcaae19           0.0              1.0
32849  ffccd5a1           0.0              4.0
32850  ffcf952b           0.0              1.0
32851  ffd62616           1.0              1.0
32852  ffd9756a           0.0              1.0
32853  ffda14ca           0.0              1.0
32854  ffdafc72           1.0              2.0
32855  ffde3628           0.0              2.0
32856  ffe066cc           0.0              1.0
32857  ffe53446           2.0              5.0
32858  ffe7e848           0.0              6.0
32859  ffeb80c5           0.0              1.0
32860  ffebdbc9           0.0              1.0
32861  ffecdf29           0.0              3.0
32862  ffed0342           1.0              7.0
32863  ffed3d0e           0.0              1.0
32864  ffee0f18           0.0              2.0
32865  ffef83e6           0.0              1.0
32866  fff1659c           0.0              3.0
32867  fff1caee           0.0              1.0
32868  fff2bdde           1.0              4.0
32869  fff72025           1.0              1.0
32870  fff78145           0.0              2.0
32871  fffd1246           0.0              1.0

[32872 rows x 3 columns]

# Promedio de conversiones respecto a los checkout

In [19]:
person_checkout_conversion["promedio"] = (person_checkout_conversion["CantidadConv"])/(person_checkout_conversion["CantidadChekout"])
person_checkout_conversion

         person  CantidadConv  CantidadChekout  promedio
0      0008ed71           0.0              3.0  0.000000
1      00091926           0.0              2.0  0.000000
2      000ba417           1.0              6.0  0.166667
3      000c79fe           0.0              1.0  0.000000
4      000e4d9e           0.0              1.0  0.000000
5      000e619d           0.0              1.0  0.000000
6      001001be           1.0              3.0  0.333333
7      0010e89a           0.0              1.0  0.000000
8      0016c4b5           0.0              1.0  0.000000
9      001802e4           0.0              1.0  0.000000
10     001804a2           1.0              2.0  0.500000
11     0019e639           2.0             15.0  0.133333
12     001a2273           0.0              1.0  0.000000
13     001b0bf9           1.0              2.0  0.500000
14     001ca5ee           0.0              1.0  0.000000
15     001e9aea           0.0              3.0  0.000000
16     0020152e           1.0              2.0  0.500000
17     00202cdb           0.0              2.0  0.000000
18     0022965d           0.0              8.0  0.000000
19     0027574e           0.0              3.0  0.000000
20     00295d74           0.0              2.0  0.000000
21     002aea56           4.0             11.0  0.363636
22     002b0188           0.0              1.0  0.000000
23     002e74b2           0.0              1.0  0.000000
24     002ed810           2.0              2.0  1.000000
25     002fb981           0.0              1.0  0.000000
26     00317e49           0.0              1.0  0.000000
27     0031c75f           0.0              2.0  0.000000
28     00344873           0.0              1.0  0.000000
29     003847fc           0.0              2.0  0.000000
...         ...           ...              ...       ...
32842  ffbb282f           0.0              1.0  0.000000
32843  ffbb90a9           0.0              1.0  0.000000
32844  ffbfc511           0.0              1.0  0.000000
32845  ffc0f2a0           0.0              4.0  0.000000
32846  ffc51f07           0.0              1.0  0.000000
32847  ffc670b3           2.0              7.0  0.285714
32848  ffcaae19           0.0              1.0  0.000000
32849  ffccd5a1           0.0              4.0  0.000000
32850  ffcf952b           0.0              1.0  0.000000
32851  ffd62616           1.0              1.0  1.000000
32852  ffd9756a           0.0              1.0  0.000000
32853  ffda14ca           0.0              1.0  0.000000
32854  ffdafc72           1.0              2.0  0.500000
32855  ffde3628           0.0              2.0  0.000000
32856  ffe066cc           0.0              1.0  0.000000
32857  ffe53446           2.0              5.0  0.400000
32858  ffe7e848           0.0              6.0  0.000000
32859  ffeb80c5           0.0              1.0  0.000000
32860  ffebdbc9           0.0              1.0  0.000000
32861  ffecdf29           0.0              3.0  0.000000
32862  ffed0342           1.0              7.0  0.142857
32863  ffed3d0e           0.0              1.0  0.000000
32864  ffee0f18           0.0              2.0  0.000000
32865  ffef83e6           0.0              1.0  0.000000
32866  fff1659c           0.0              3.0  0.000000
32867  fff1caee           0.0              1.0  0.000000
32868  fff2bdde           1.0              4.0  0.250000
32869  fff72025           1.0              1.0  1.000000
32870  fff78145           0.0              2.0  0.000000
32871  fffd1246           0.0              1.0  0.000000

[32872 rows x 4 columns]

In [20]:
person_frecuencia = person_checkout_conversion.loc[:,["person","promedio"]]
person_frecuencia["promedio"] = person_frecuencia.promedio.astype('float64')
person_frecuencia

         person  promedio
0      0008ed71  0.000000
1      00091926  0.000000
2      000ba417  0.166667
3      000c79fe  0.000000
4      000e4d9e  0.000000
5      000e619d  0.000000
6      001001be  0.333333
7      0010e89a  0.000000
8      0016c4b5  0.000000
9      001802e4  0.000000
10     001804a2  0.500000
11     0019e639  0.133333
12     001a2273  0.000000
13     001b0bf9  0.500000
14     001ca5ee  0.000000
15     001e9aea  0.000000
16     0020152e  0.500000
17     00202cdb  0.000000
18     0022965d  0.000000
19     0027574e  0.000000
20     00295d74  0.000000
21     002aea56  0.363636
22     002b0188  0.000000
23     002e74b2  0.000000
24     002ed810  1.000000
25     002fb981  0.000000
26     00317e49  0.000000
27     0031c75f  0.000000
28     00344873  0.000000
29     003847fc  0.000000
...         ...       ...
32842  ffbb282f  0.000000
32843  ffbb90a9  0.000000
32844  ffbfc511  0.000000
32845  ffc0f2a0  0.000000
32846  ffc51f07  0.000000
32847  ffc670b3  0.285714
32848  ffcaae19  0.000000
32849  ffccd5a1  0.000000
32850  ffcf952b  0.000000
32851  ffd62616  1.000000
32852  ffd9756a  0.000000
32853  ffda14ca  0.000000
32854  ffdafc72  0.500000
32855  ffde3628  0.000000
32856  ffe066cc  0.000000
32857  ffe53446  0.400000
32858  ffe7e848  0.000000
32859  ffeb80c5  0.000000
32860  ffebdbc9  0.000000
32861  ffecdf29  0.000000
32862  ffed0342  0.142857
32863  ffed3d0e  0.000000
32864  ffee0f18  0.000000
32865  ffef83e6  0.000000
32866  fff1659c  0.000000
32867  fff1caee  0.000000
32868  fff2bdde  0.250000
32869  fff72025  1.000000
32870  fff78145  0.000000
32871  fffd1246  0.000000

[32872 rows x 2 columns]

In [21]:
person_frecuencia["Frecuente"] = person_frecuencia.promedio >= 0.6
person_frecuencia["Esporadicos"] = (person_frecuencia.promedio > 0.2) & (person_frecuencia.promedio < 0.6)
person_frecuencia["Casi nunca"] = (person_frecuencia.promedio <= 0.2)  & (person_frecuencia.promedio > 0)
person_frecuencia["Nunca"] = (person_frecuencia.promedio == 0)
person_frecuencia

         person  promedio  Frecuente  Esporadicos  Casi nunca  Nunca
0      0008ed71  0.000000      False        False       False   True
1      00091926  0.000000      False        False       False   True
2      000ba417  0.166667      False        False        True  False
3      000c79fe  0.000000      False        False       False   True
4      000e4d9e  0.000000      False        False       False   True
5      000e619d  0.000000      False        False       False   True
6      001001be  0.333333      False         True       False  False
7      0010e89a  0.000000      False        False       False   True
8      0016c4b5  0.000000      False        False       False   True
9      001802e4  0.000000      False        False       False   True
10     001804a2  0.500000      False         True       False  False
11     0019e639  0.133333      False        False        True  False
12     001a2273  0.000000      False        False       False   True
13     001b0bf9  0.500000      False         True       False  False
14     001ca5ee  0.000000      False        False       False   True
15     001e9aea  0.000000      False        False       False   True
16     0020152e  0.500000      False         True       False  False
17     00202cdb  0.000000      False        False       False   True
18     0022965d  0.000000      False        False       False   True
19     0027574e  0.000000      False        False       False   True
20     00295d74  0.000000      False        False       False   True
21     002aea56  0.363636      False         True       False  False
22     002b0188  0.000000      False        False       False   True
23     002e74b2  0.000000      False        False       False   True
24     002ed810  1.000000       True        False       False  False
25     002fb981  0.000000      False        False       False   True
26     00317e49  0.000000      False        False       False   True
27     0031c75f  0.000000      False        False       False   True
28     00344873  0.000000      False        False       False   True
29     003847fc  0.000000      False        False       False   True
...         ...       ...        ...          ...         ...    ...
32842  ffbb282f  0.000000      False        False       False   True
32843  ffbb90a9  0.000000      False        False       False   True
32844  ffbfc511  0.000000      False        False       False   True
32845  ffc0f2a0  0.000000      False        False       False   True
32846  ffc51f07  0.000000      False        False       False   True
32847  ffc670b3  0.285714      False         True       False  False
32848  ffcaae19  0.000000      False        False       False   True
32849  ffccd5a1  0.000000      False        False       False   True
32850  ffcf952b  0.000000      False        False       False   True
32851  ffd62616  1.000000       True        False       False  False
32852  ffd9756a  0.000000      False        False       False   True
32853  ffda14ca  0.000000      False        False       False   True
32854  ffdafc72  0.500000      False         True       False  False
32855  ffde3628  0.000000      False        False       False   True
32856  ffe066cc  0.000000      False        False       False   True
32857  ffe53446  0.400000      False         True       False  False
32858  ffe7e848  0.000000      False        False       False   True
32859  ffeb80c5  0.000000      False        False       False   True
32860  ffebdbc9  0.000000      False        False       False   True
32861  ffecdf29  0.000000      False        False       False   True
32862  ffed0342  0.142857      False        False        True  False
32863  ffed3d0e  0.000000      False        False       False   True
32864  ffee0f18  0.000000      False        False       False   True
32865  ffef83e6  0.000000      False        False       False   True
32866  fff1659c  0.000000      False        False       False   True
32867  fff1caee  0.000000      False        False       False   True
32868  fff2bdde  0.250000      False         True       False  False
32869  fff72025  1.000000       True        False       False  False
32870  fff78145  0.000000      False        False       False   True
32871  fffd1246  0.000000      False        False       False   True

[32872 rows x 6 columns]

In [22]:
otro = person_frecuencia.loc[:, ["person","Frecuente","Esporadicos","Casi nunca","Nunca"]]

In [23]:
otro

         person  Frecuente  Esporadicos  Casi nunca  Nunca
0      0008ed71      False        False       False   True
1      00091926      False        False       False   True
2      000ba417      False        False        True  False
3      000c79fe      False        False       False   True
4      000e4d9e      False        False       False   True
5      000e619d      False        False       False   True
6      001001be      False         True       False  False
7      0010e89a      False        False       False   True
8      0016c4b5      False        False       False   True
9      001802e4      False        False       False   True
10     001804a2      False         True       False  False
11     0019e639      False        False        True  False
12     001a2273      False        False       False   True
13     001b0bf9      False         True       False  False
14     001ca5ee      False        False       False   True
15     001e9aea      False        False       False   True
16     0020152e      False         True       False  False
17     00202cdb      False        False       False   True
18     0022965d      False        False       False   True
19     0027574e      False        False       False   True
20     00295d74      False        False       False   True
21     002aea56      False         True       False  False
22     002b0188      False        False       False   True
23     002e74b2      False        False       False   True
24     002ed810       True        False       False  False
25     002fb981      False        False       False   True
26     00317e49      False        False       False   True
27     0031c75f      False        False       False   True
28     00344873      False        False       False   True
29     003847fc      False        False       False   True
...         ...        ...          ...         ...    ...
32842  ffbb282f      False        False       False   True
32843  ffbb90a9      False        False       False   True
32844  ffbfc511      False        False       False   True
32845  ffc0f2a0      False        False       False   True
32846  ffc51f07      False        False       False   True
32847  ffc670b3      False         True       False  False
32848  ffcaae19      False        False       False   True
32849  ffccd5a1      False        False       False   True
32850  ffcf952b      False        False       False   True
32851  ffd62616       True        False       False  False
32852  ffd9756a      False        False       False   True
32853  ffda14ca      False        False       False   True
32854  ffdafc72      False         True       False  False
32855  ffde3628      False        False       False   True
32856  ffe066cc      False        False       False   True
32857  ffe53446      False         True       False  False
32858  ffe7e848      False        False       False   True
32859  ffeb80c5      False        False       False   True
32860  ffebdbc9      False        False       False   True
32861  ffecdf29      False        False       False   True
32862  ffed0342      False        False        True  False
32863  ffed3d0e      False        False       False   True
32864  ffee0f18      False        False       False   True
32865  ffef83e6      False        False       False   True
32866  fff1659c      False        False       False   True
32867  fff1caee      False        False       False   True
32868  fff2bdde      False         True       False  False
32869  fff72025       True        False       False  False
32870  fff78145      False        False       False   True
32871  fffd1246      False        False       False   True

[32872 rows x 5 columns]

In [24]:
otro["Frecuencia"] = "nada"
otro.loc[(otro["Esporadicos"] == True), "Frecuencia"] = "Esporadico"
otro.loc[(otro["Frecuente"] == True), "Frecuencia"] = "Frecuente"
otro.loc[(otro["Casi nunca"] == True), "Frecuencia"] = "Casi nunca"
otro.loc[(otro["Nunca"] == True), "Frecuencia"] = "Nunca"

otro.loc[:, ["person","Frecuencia"]]

         person  Frecuencia
0      0008ed71       Nunca
1      00091926       Nunca
2      000ba417  Casi nunca
3      000c79fe       Nunca
4      000e4d9e       Nunca
5      000e619d       Nunca
6      001001be  Esporadico
7      0010e89a       Nunca
8      0016c4b5       Nunca
9      001802e4       Nunca
10     001804a2  Esporadico
11     0019e639  Casi nunca
12     001a2273       Nunca
13     001b0bf9  Esporadico
14     001ca5ee       Nunca
15     001e9aea       Nunca
16     0020152e  Esporadico
17     00202cdb       Nunca
18     0022965d       Nunca
19     0027574e       Nunca
20     00295d74       Nunca
21     002aea56  Esporadico
22     002b0188       Nunca
23     002e74b2       Nunca
24     002ed810   Frecuente
25     002fb981       Nunca
26     00317e49       Nunca
27     0031c75f       Nunca
28     00344873       Nunca
29     003847fc       Nunca
...         ...         ...
32842  ffbb282f       Nunca
32843  ffbb90a9       Nunca
32844  ffbfc511       Nunca
32845  ffc0f2a0       Nunca
32846  ffc51f07       Nunca
32847  ffc670b3  Esporadico
32848  ffcaae19       Nunca
32849  ffccd5a1       Nunca
32850  ffcf952b       Nunca
32851  ffd62616   Frecuente
32852  ffd9756a       Nunca
32853  ffda14ca       Nunca
32854  ffdafc72  Esporadico
32855  ffde3628       Nunca
32856  ffe066cc       Nunca
32857  ffe53446  Esporadico
32858  ffe7e848       Nunca
32859  ffeb80c5       Nunca
32860  ffebdbc9       Nunca
32861  ffecdf29       Nunca
32862  ffed0342  Casi nunca
32863  ffed3d0e       Nunca
32864  ffee0f18       Nunca
32865  ffef83e6       Nunca
32866  fff1659c       Nunca
32867  fff1caee       Nunca
32868  fff2bdde  Esporadico
32869  fff72025   Frecuente
32870  fff78145       Nunca
32871  fffd1246       Nunca

[32872 rows x 2 columns]

In [27]:
person_Ff = df.loc[df.person == "ffd62616"]
person_Ff.event.value_counts()

visited site         31
generic listing      21
brand listing        12
staticpage           11
viewed product       11
ad campaign hit      11
search engine hit     7
conversion            1
checkout              1
Name: event, dtype: int64