In [1]:
from numpy import loadtxt
#from xgboost import XGBClassifier
#from sklearn.model_selection import train_test_split
#from sklearn.metrics import accuracy_score
import pandas as pd
import seaborn as sns

In [2]:
events = pd.read_csv('../dataset/events_up_to_01062018.csv', low_memory = False)
test = pd.read_csv('../dataset/labels_training_set.csv')

In [3]:
events.head()

,timestamp,event,person,url,sku,model,condition,storage,color,skus,...,search_engine,channel,new_vs_returning,city,region,country,device_type,screen_resolution,operating_system_version,browser_version
0,2018-05-18 00:11:59,viewed product,4886f805,NaN,9288.0,Samsung Galaxy J7 Prime,Excelente,32GB,Dourado,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2018-05-18 00:11:27,viewed product,ad93850f,NaN,304.0,iPhone 5s,Muito Bom,32GB,Cinza espacial,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2018-05-18 00:11:16,viewed product,0297fc1e,NaN,6888.0,iPhone 6S,Muito Bom,64GB,Prateado,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2018-05-18 00:11:14,viewed product,2d681dd8,NaN,11890.0,iPhone 7,Bom,128GB,Vermelho,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2018-05-18 00:11:09,viewed product,cccea85e,NaN,7517.0,LG G4 H818P,Excelente,32GB,Branco,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
#CREO UN DATA FRAME CON LAS PERSONAS PARA IR JOINEANDO MIS FEATURES AHI
persons = events['person'].to_frame().drop_duplicates()
persons.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 38829 entries, 0 to 2341657
Data columns (total 1 columns):
person    38829 non-null object
dtypes: object(1)
memory usage: 606.7+ KB

In [5]:
#ELIMINO COLUMNA MODEL YA QUE TENEMOS EL SKU QUE ES UN VALOR NUMERICO (MEJOR PARA LOS ALGORITMOS DE ML) REPRESENTANDO
#EL MODELO
events = events.drop(columns='model')

#TRANSFROMO LA FECHA A TIMESTAMP
events['timestamp'] = pd.to_datetime(events['timestamp'])

In [6]:
#AGREGO UNA COLUMNA DE CANTIDAD
events['cantidad'] = 1

In [7]:
#HACIENDO ESTE GROUPBY NOS QUEDAMOS CON LOS SKUS QUE VIO UNA PERSONA Y EN QUE FECHAg
grouped_sku = events.groupby(['person','sku']).agg({'cantidad':'sum'})
grouped_sku.sort_values(by='cantidad', ascending=False, inplace=True)
#grouped_sku.drop_duplicates(inplace=True, , keep='first')
grouped_sku = grouped_sku.reset_index().drop_duplicates(keep='first', subset='person')
grouped_sku.drop(columns='cantidad', inplace=True)
grouped_sku.columns = ['person', 'most_viewed_sku']
grouped_sku.info()
persons = pd.merge(persons, grouped_sku, how='left', on='person')
persons.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 38250 entries, 0 to 622391
Data columns (total 2 columns):
person             38250 non-null object
most_viewed_sku    38250 non-null float64
dtypes: float64(1), object(1)
memory usage: 896.5+ KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 38829 entries, 0 to 38828
Data columns (total 2 columns):
person             38829 non-null object
most_viewed_sku    38250 non-null float64
dtypes: float64(1), object(1)
memory usage: 910.1+ KB

In [8]:
conversions = events.loc[events['event'] == 'conversion']
#checkouts = events.loc[events['event'] == 'checkout']
#viewed_products = events.loc[events['event'] == 'viewed product']
#sns.countplot(data=conversions, x='sku', order=conversions.sku.value_counts().head(5).index)

In [9]:
#DATAFRAME DE USUARIOS QUE REALIZARON UNA CONVERSION
grouped_conversions = conversions.groupby(['person']).agg({'cantidad':'count'})
grouped_conversions.reset_index(inplace=True)
person_converted = grouped_conversions.drop(columns='cantidad')
person_converted['has_converted_before'] = 1
persons = pd.merge(person_converted, persons, how='right', on='person')

In [10]:
#HACIENDO ESTE GROUPBY NOS QUEDAMOS CON LOS SKUS QUE VIO UNA PERSONA Y EN QUE FECHAg
grouped_color = events.groupby(['person','color']).agg({'cantidad':'sum'})
grouped_color.sort_values(by='cantidad', ascending=False, inplace=True)
#grouped_sku.drop_duplicates(inplace=True, , keep='first')
grouped_color = grouped_color.reset_index().drop_duplicates(keep='first', subset='person')
grouped_color.drop(columns='cantidad', inplace=True)
grouped_color.columns = ['person', 'most_viewed_color']
grouped_color.info()
persons = pd.merge(persons, grouped_color, how='left', on='person')
persons.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 38250 entries, 0 to 167672
Data columns (total 2 columns):
person               38250 non-null object
most_viewed_color    38250 non-null object
dtypes: object(2)
memory usage: 896.5+ KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 38829 entries, 0 to 38828
Data columns (total 4 columns):
person                  38829 non-null object
has_converted_before    4293 non-null float64
most_viewed_sku         38250 non-null float64
most_viewed_color       38250 non-null object
dtypes: float64(2), object(2)
memory usage: 1.5+ MB

In [11]:
grouped_region = events.groupby(['person','region']).agg({'cantidad':'sum'})
grouped_region.sort_values(by='cantidad', ascending=False, inplace=True)
grouped_region = grouped_region.reset_index().drop_duplicates(keep='first', subset='person')
grouped_region.drop(columns='cantidad', inplace=True)
grouped_region.columns = ['person', 'region_brasil']
persons = pd.merge(persons, grouped_region, how='left', on= 'person')

In [12]:
persons

,person,has_converted_before,most_viewed_sku,most_viewed_color,region_brasil
0,000ba417,1.0,2988.0,Preto,Sao Paulo
1,001001be,1.0,290.0,Dourado,Sao Paulo
2,001804a2,1.0,2831.0,Dourado,Unknown
3,0019e639,1.0,2750.0,Preto,Sao Paulo
4,001b0bf9,1.0,12788.0,Ametista,NaN
5,0020152e,1.0,7251.0,Dourado,Rio Grande do Sul
6,002aea56,1.0,8233.0,Cinza espacial,Mato Grosso
7,002ed810,1.0,8443.0,Preto,Santa Catarina
8,0038a117,1.0,13613.0,Preto,Unknown
9,0043a48e,1.0,3288.0,Preto,Unknown
10,004ed8ba,1.0,12282.0,Preto,Unknown
11,00546f4c,1.0,8287.0,Dourado,Bahia
12,00750af8,1.0,8441.0,Preto,Minas Gerais
13,0076b7dc,1.0,8261.0,Ouro Rosa,Pernambuco
14,00971729,1.0,10351.0,Preto,Sao Paulo
15,009944e1,1.0,10366.0,Preto,Sao Paulo
16,009f8292,1.0,283.0,Cinza espacial,Unknown
17,00caa482,1.0,122.0,Preto,Minas Gerais
18,00cd1373,1.0,178.0,Branco,Goias
19,00ecfd1a,1.0,9287.0,Dourado,Maranhao
20,00fa4cd7,1.0,8499.0,Rosa,Rio de Janeiro
21,01039bf1,1.0,9272.0,Preto,Unknown
22,010b0b0b,1.0,7658.0,Dourado,Bahia
23,011beb42,1.0,7001.0,Prateado,Sao Paulo
24,0137a57b,1.0,9903.0,Preto Brilhante,Rio de Janeiro
25,0163bf88,1.0,7239.0,Preto,Minas Gerais
26,016a78e4,1.0,2709.0,Preto,Minas Gerais
27,016b86b9,1.0,2750.0,Preto,Sao Paulo
28,016f3833,1.0,1061.0,Branco,Arkansas
29,017fd805,1.0,2695.0,Dourado,Sao Paulo
...,...,...,...,...,...
38799,154d2935,NaN,NaN,NaN,NaN
38800,3adf7ca4,NaN,NaN,NaN,Rio de Janeiro
38801,c9552fad,NaN,NaN,NaN,Bahia
38802,2e89874a,NaN,NaN,NaN,NaN
38803,ef4e52ab,NaN,NaN,NaN,Sao Paulo
38804,100f33c8,NaN,NaN,NaN,Sao Paulo
38805,90251b6a,NaN,NaN,NaN,NaN
38806,85e0f62a,NaN,NaN,NaN,Rondonia
38807,0afaecc8,NaN,NaN,NaN,Rondonia
38808,2c209f87,NaN,NaN,NaN,Unknown
38809,4ddb8c19,NaN,NaN,NaN,Mato Grosso do Sul
38810,9979305a,NaN,NaN,NaN,Mato Grosso do Sul
38811,25bd8078,NaN,NaN,NaN,Sao Paulo
38812,87d306fc,NaN,NaN,NaN,Sao Paulo
38813,a2b1e355,NaN,NaN,NaN,Unknown
38814,fb88a7ea,NaN,NaN,NaN,Ceara
38815,1315ce31,NaN,NaN,NaN,Sao Paulo
38816,af3374ad,NaN,NaN,NaN,Unknown
38817,023581f9,NaN,NaN,NaN,Minas Gerais
38818,9707cd0e,NaN,NaN,NaN,Sao Paulo
38819,88b91c5d,NaN,NaN,NaN,Santa Catarina
38820,6f7632db,NaN,NaN,NaN,Unknown
38821,a1c2a901,NaN,NaN,NaN,Sergipe
38822,ed3f80d7,NaN,NaN,NaN,Sao Paulo
38823,2adb3684,NaN,NaN,NaN,Unknown
38824,39fa45b6,NaN,NaN,NaN,Sao Paulo
38825,92f2d94b,NaN,NaN,NaN,NaN
38826,d8d6b0da,NaN,NaN,NaN,NaN
38827,40bf23ab,NaN,NaN,NaN,NaN
38828,80aea0a0,NaN,NaN,NaN,NaN

In [42]:
persons.fillna(value=0, inplace=True)
persons_dummies = pd.get_dummies(persons, columns=['most_viewed_color', 'region_brasil'])
persons_filtered = persons_dummies[['person',
                                    'has_converted_before','most_viewed_sku','most_viewed_color_Preto',
                                   'most_viewed_color_Branco','most_viewed_color_Dourado', 'region_brasil_Sao Paulo',
                                   'region_brasil_Unknown', 'region_brasil_Minas Gerais']]

In [43]:
persons_filtered.to_csv('../features/features_gonza.csv')

In [44]:
persons_filtered

,has_converted_before,most_viewed_sku,most_viewed_color_Preto,most_viewed_color_Branco,most_viewed_color_Dourado,region_brasil_Sao Paulo,region_brasil_Unknown,region_brasil_Minas Gerais
0,1.0,2988.0,1,0,0,1,0,0
1,1.0,290.0,0,0,1,1,0,0
2,1.0,2831.0,0,0,1,0,1,0
3,1.0,2750.0,1,0,0,1,0,0
4,1.0,12788.0,0,0,0,0,0,0
5,1.0,7251.0,0,0,1,0,0,0
6,1.0,8233.0,0,0,0,0,0,0
7,1.0,8443.0,1,0,0,0,0,0
8,1.0,13613.0,1,0,0,0,1,0
9,1.0,3288.0,1,0,0,0,1,0
10,1.0,12282.0,1,0,0,0,1,0
11,1.0,8287.0,0,0,1,0,0,0
12,1.0,8441.0,1,0,0,0,0,1
13,1.0,8261.0,0,0,0,0,0,0
14,1.0,10351.0,1,0,0,1,0,0
15,1.0,10366.0,1,0,0,1,0,0
16,1.0,283.0,0,0,0,0,1,0
17,1.0,122.0,1,0,0,0,0,1
18,1.0,178.0,0,1,0,0,0,0
19,1.0,9287.0,0,0,1,0,0,0
20,1.0,8499.0,0,0,0,0,0,0
21,1.0,9272.0,1,0,0,0,1,0
22,1.0,7658.0,0,0,1,0,0,0
23,1.0,7001.0,0,0,0,1,0,0
24,1.0,9903.0,0,0,0,0,0,0
25,1.0,7239.0,1,0,0,0,0,1
26,1.0,2709.0,1,0,0,0,0,1
27,1.0,2750.0,1,0,0,1,0,0
28,1.0,1061.0,0,1,0,0,0,0
29,1.0,2695.0,0,0,1,1,0,0
...,...,...,...,...,...,...,...,...
38799,0.0,0.0,0,0,0,0,0,0
38800,0.0,0.0,0,0,0,0,0,0
38801,0.0,0.0,0,0,0,0,0,0
38802,0.0,0.0,0,0,0,0,0,0
38803,0.0,0.0,0,0,0,1,0,0
38804,0.0,0.0,0,0,0,1,0,0
38805,0.0,0.0,0,0,0,0,0,0
38806,0.0,0.0,0,0,0,0,0,0
38807,0.0,0.0,0,0,0,0,0,0
38808,0.0,0.0,0,0,0,0,1,0
38809,0.0,0.0,0,0,0,0,0,0
38810,0.0,0.0,0,0,0,0,0,0
38811,0.0,0.0,0,0,0,1,0,0
38812,0.0,0.0,0,0,0,1,0,0
38813,0.0,0.0,0,0,0,0,1,0
38814,0.0,0.0,0,0,0,0,0,0
38815,0.0,0.0,0,0,0,1,0,0
38816,0.0,0.0,0,0,0,0,1,0
38817,0.0,0.0,0,0,0,0,0,1
38818,0.0,0.0,0,0,0,1,0,0
38819,0.0,0.0,0,0,0,0,0,0
38820,0.0,0.0,0,0,0,0,1,0
38821,0.0,0.0,0,0,0,0,0,0
38822,0.0,0.0,0,0,0,1,0,0
38823,0.0,0.0,0,0,0,0,1,0
38824,0.0,0.0,0,0,0,1,0,0
38825,0.0,0.0,0,0,0,0,0,0
38826,0.0,0.0,0,0,0,0,0,0
38827,0.0,0.0,0,0,0,0,0,0
38828,0.0,0.0,0,0,0,0,0,0

In [45]:
events['timestamp'] = pd.to_datetime(events['timestamp'])
events['month'] = events['timestamp'].dt.month
conversions_month = events.loc[events['event'] == 'conversion']
conversions_month = conversions_month.groupby('month').agg({'cantidad':'count'})

In [46]:
conversions_f = pd.merge(conversions, persons, how='inner', on='person')

In [18]:
conversions_f.region_brasil_S

AttributeError: 'DataFrame' object has no attribute 'region_brasil_S'